name: getx_prj_base
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  get: 4.6.1
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.0
  flutter_easyloading: ^3.0.3
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.3.1
  dio: ^4.0.6

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/locales/

